In [106]:
#importing all the libraries
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
#read the csv file
creditcard=pd.read_csv("C:/Users/91801/Downloads/creditcard.csv")

In [15]:
creditcard.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [16]:
creditcard.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [18]:
creditcard.shape

(284807, 31)

In [19]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [21]:
creditcard['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [70]:
legid=creditcard[creditcard.Class == 0]
fraud=creditcard[creditcard.Class == 1]

In [72]:
fraud.shape

(492, 31)

In [71]:
legid.shape

(284315, 31)

In [25]:
creditcard.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [26]:
creditcard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [27]:
creditcard.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [74]:
legid.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [75]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [77]:
legid_sample=legid.sample(n=492)

In [84]:
new_dataset=pd.concat([legid_sample,fraud],axis=0)

In [85]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
141122,84135.0,-1.100208,-0.448551,1.544816,-0.300550,-1.278800,0.095534,1.530862,-0.150530,-1.264930,...,-0.149196,-0.339488,0.481078,0.325192,0.510099,-0.455735,0.008364,0.125253,330.26,0
123281,76869.0,-0.491743,0.750773,1.917319,0.975377,0.133268,0.304098,0.364428,0.241377,-0.539482,...,-0.044965,0.037746,-0.000116,0.220473,-0.393935,-0.524384,0.190349,0.144785,12.99,0
134219,80702.0,1.200431,0.222461,0.117736,1.088447,-0.433464,-0.808942,-0.106797,-0.073914,0.653771,...,-0.185469,-0.312945,-0.089589,0.325673,0.533212,0.412315,-0.001457,0.042225,12.31,0
168338,119176.0,2.104610,-0.336702,-1.910514,-0.004467,0.412695,-0.270131,-0.052901,-0.021051,0.617196,...,0.310115,0.968020,-0.134579,0.149893,0.343968,1.002429,-0.117968,-0.093971,2.25,0
19850,30598.0,1.067199,0.036251,0.272360,1.105103,-0.254046,-0.243896,0.005816,0.217938,-0.011782,...,-0.402867,-1.446547,0.243133,-0.132562,0.036523,-0.819121,-0.002682,0.016758,44.98,0

In [86]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [87]:
new_dataset.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,89300.185976,-2.380790,1.867421,-3.570040,2.271262,-1.569432,-0.716986,-2.840914,0.225850,-1.257890,...,0.360939,0.017384,-0.012713,-0.016553,0.039355,0.046527,0.064817,0.028058,97.012480,0.500000
std,47949.588050,5.551889,3.689827,6.202102,3.188135,4.224651,1.760129,5.839064,4.991725,2.353838,...,2.895715,1.187383,1.166634,0.545743,0.671020,0.490838,1.037116,0.454403,214.577832,0.500254
min,406.000000,-30.552380,-10.525218,-31.103685,-3.579418,-22.105532,-6.923348,-43.557242,-41.044261,-13.434066,...,-22.797604,-8.887017,-19.254328,-2.028024,-4.781606,-1.282354,-7.263482,-2.250654,0.000000,0.000000
25%,49153.750000,-2.964835,-0.154383,-5.138122,-0.092709,-1.773254,-1.590711,-3.119040,-0.223399,-2.312932,...,-0.174020,-0.523657,-0.236505,-0.373302,-0.312025,-0.276953,-0.078573,-0.065144,1.290000,0.000000
50%,81162.000000,-0.740731,0.957344,-1.484875,1.276455,-0.445837,-0.664197,-0.682656,0.133286,-0.706902,...,0.152129,0.037722,-0.041723,0.022409,0.089700,-0.009778,0.034640,0.025425,15.990000,0.500000
75%,136908.000000,1.095789,2.930212,0.214312,4.276079,0.480665,0.049922,0.222150,0.866177,0.184695,...,0.669102,0.584340,0.199918,0.388118,0.402352,0.375486,0.436197,0.216196,99.862500,1.000000
max,171902.000000,2.329549,22.057729,3.321769,12.114672,11.095089,6.642617,7.242949,20.007208,5.515948,...,27.202839,8.361985,5.466230,1.238952,2.208209,2.745261,3.052358,4.674074,2125.870000,1.000000

In [88]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [89]:
X=new_dataset.drop(columns='Class',axis=1)

In [90]:
Y=new_dataset['Class']

In [91]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
141122   84135.0 -1.100208 -0.448551  1.544816 -0.300550 -1.278800  0.095534
123281   76869.0 -0.491743  0.750773  1.917319  0.975377  0.133268  0.304098
134219   80702.0  1.200431  0.222461  0.117736  1.088447 -0.433464 -0.808942
168338  119176.0  2.104610 -0.336702 -1.910514 -0.004467  0.412695 -0.270131
19850    30598.0  1.067199  0.036251  0.272360  1.105103 -0.254046 -0.243896
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
141122  1.530862 -0.150530 -1.264930  ...  0.144241 -0.149196 -0.339488
123281  0.364428  0.241377 -0.539482  ...  0.036221 -0.044965  0.037746
134219 -0.106797 -0.073914  0.653771  ... -0.101011 -0.185469 -0.312945
168338 -0.052901 -0.021051  0.617196  ... -0.302238  0.310115  0.968020
19850   0.005816  0.217938 -0.011782  ... -0.268862 -0.402867 -1.446547
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
141122  0.481078  0.325192  0.510099 -0.455735  0.008364  0.125253  330.26
123281 -0.000116  0.220473 -0.393935 -0.524384  0.190349  0.144785   12.99
134219 -0.089589  0.325673  0.533212  0.412315 -0.001457  0.042225   12.31
168338 -0.134579  0.149893  0.343968  1.002429 -0.117968 -0.093971    2.25
19850   0.243133 -0.132562  0.036523 -0.819121 -0.002682  0.016758   44.98
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [92]:
print(Y)

141122    0
123281    0
134219    0
168338    0
19850     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [93]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [94]:
print(X.shape)

(984, 30)

In [95]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [96]:
print(Y.shape,Y_train.shape,Y_test.shape)

(984,) (787,) (197,)

In [105]:
model = LogisticRegression()

In [107]:
model.fit(X_train, Y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [108]:
X_train_prediction=model.predict(X_train)

In [109]:
X_train_accuracyscore=accuracy_score(X_train_prediction,Y_train)

In [110]:
print("Accuracy of train data set = ",X_train_accuracyscore)

Accuracy of train data set =  0.9466327827191868

In [111]:
X_test_prediction=model.predict(X_test)

In [112]:
X_test_accuracyscore=accuracy_score(X_test_prediction,Y_test)

In [113]:
print("Accuracy score of the test data set = ",X_test_accuracyscore)

Accuracy score of the test data set =  0.9187817258883249